name: demo_linkup_mapp
description: Link-Up App Prototype

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_statusbarcolor: ^0.2.3

  cupertino_icons: ^1.0.0

  shared_preferences: ^0.5.12+4

  provider: ^4.3.2+3

  get: ^3.24.0

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0

  multi_select_flutter: ^3.1.6
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1

  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_name: "^0.0.1"

  flutter_launcher_icons: "^0.8.0"

flutter:

  uses-material-design: true

  assets:
  - assets/images/link-up-media/
  - assets/images/social-media-logos/
  - assets/images/usuarios/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

flutter_launcher_name:
  name: "Link-Up Demo"

flutter_icons:
  image_path: "assets/images/link-up-media/icon.png"
  android: true